- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: delete html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create new HTML directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the front end code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: unzip the frontend
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy expense file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart Nginx


