- name: install MYSQL libraries using Python
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: MYSQL server configuration
  ansible.builtin.package:
    name: mysql-server
    state: installed
  
- name: Create and enable MYSQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Connecting MYSQL DB
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: mysql.kumardevops.store
  register: mysql_info
  ignore_errors: true

- name: print the output
  ansible.builtin.debug:
    msg: "MYSQL Info: {{ mysql_info }}"
  
- name: setup root password
  ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_info.failed is true
