- name: Configuring dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: "pip3.9"
  loop:
  - Cryptography
  - PyMySQL

- name: Installing MYSQL server
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: Enable & start the MYSQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Connect to MYSQL server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ MYSQL_HOST }}"
  register: mysql_info
  ignore_errors: true

- name: Print the connection output status
  ansible.builtin.debug:
    msg: "MySQL info is : {{ mysql_info }}"

- name: Setup the root password when the connection failed/ password not there
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_info.failed is true
